# services:
#   server:
#     build: ./server
#     ports:
#       - "8000:8000"
#     env_file:
#       - ./server/.env
#     volumes:
#       - ./server:/app
#     depends_on:
#       - mongodb

#   client:
#     build: ./client
#     ports:
#       - "5173:5173"
#     volumes:
#       - ./client:/app
#     depends_on:
#       - server

#   mongodb:
#     image: mongo:latest
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db

# volumes:
#   mongo-data:

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    depends_on:
      - mongodb

  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    depends_on:
      - server

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
